export const seasonal = {
  spring: [
    { day: 1, name: "파슬리", image: "/assets/images/crops/parsley.png" },
    { day: 1, name: "양배추", image: "/assets/images/crops/cabbage.png" },
    { day: 2, name: "딸기", image: "/assets/images/crops/strawberry.png" },
    { day: 2, name: "양파", image: "/assets/images/crops/onion.png" },
    { day: 3, name: "브로콜리", image: "/assets/images/crops/broccoli.png" },
    {
      day: 4,
      name: "아스파라거스",
      image: "/assets/images/crops/asparagus.png",
    },
    { day: 5, name: "아티초크", image: "/assets/images/crops/artichoke.png" },
  ],
  summer: [
    { day: 1, name: "토마토", image: "/assets/images/crops/tomato.png" },
    { day: 1, name: "옥수수", image: "/assets/images/crops/corn.png" },
    { day: 2, name: "고추", image: "/assets/images/crops/chili.png" },
    { day: 2, name: "블루베리", image: "/assets/images/crops/blueberry.png" },
    { day: 2, name: "멜론", image: "/assets/images/crops/melon.png" },
    { day: 3, name: "가지", image: "/assets/images/crops/eggplant.png" },
    { day: 3, name: "파인애플", image: "/assets/images/crops/pineapple.png" },
    { day: 3, name: "바나나", image: "/assets/images/crops/banana.png" },
    { day: 4, name: "파프리카", image: "/assets/images/crops/paprika.png" },
    { day: 4, name: "망고", image: "/assets/images/crops/mango.png" },
    { day: 5, name: "복숭아", image: "/assets/images/crops/peach.png" },
  ],
  autumn: [
    { day: 1, name: "콩", image: "/assets/images/crops/soybean.png" },
    { day: 2, name: "무", image: "/assets/images/crops/radish.png" },
    { day: 2, name: "쌀", image: "/assets/images/crops/rice.png" },
    { day: 3, name: "배추", image: "/assets/images/crops/napa_cabbage.png" },
    { day: 3, name: "포도", image: "/assets/images/crops/grape.png" },
    { day: 4, name: "고구마", image: "/assets/images/crops/sweet_potato.png" },
    { day: 5, name: "산삼", image: "/assets/images/crops/ginseng.png" },
  ],
  winter: [
    { day: 2, name: "파", image: "/assets/images/crops/green_onion.png" },
    { day: 3, name: "순무", image: "/assets/images/crops/turnip.png" },
    { day: 3, name: "레몬", image: "/assets/images/crops/lemon.png" },
    { day: 4, name: "마늘", image: "/assets/images/crops/garlic.png" },
    { day: 5, name: "오렌지", image: "/assets/images/crops/orange.png" },
  ],
};
